### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Kongledyret** [Bigjoos/U-232-V3#15]
Hi!

I'm getting this error when logging in: 

MySQLI Error

There appears to be an error with the database.
You can try to refresh the page by clicking here

Memcache installed, mysqli installed.

**Comment by whocares-openscene** [comment]
Check in your root dir/logs for the most recent log file, it should give a specific error.

**Comment by Kongledyret** [comment]
Can't find anything wrong there. Or I might be blind

**Comment by whocares-openscene** [comment]
What is in the most recent file?

**Comment by Kongledyret** [comment]
auth.log

**Comment by whocares-openscene** [comment]
it should be in something like /var/www/logs
there should be something like sql_err_date.log

**Comment by Kongledyret** [comment]
No such log as you are mentioning from today's date :/

**Comment by Kongledyret** [comment]
Found it, was missing some permissions, then it wrote log.

**Comment by Kongledyret** [comment]
Fixed! Ty
