### ISSUE TITLE
Irc Announce

### ISSUE THREAD

**Issue by Kongledyret** [Bigjoos/U-232-V3#16]
Hi!

I'm trying to get the IRC Announce to work. I have setup all needed files, but when I uncomment

if ($INSTALLER09['autoshout_on'] == 1) {
    autoshout($message);
    //ircbot($messages); <--- I get 505 blank page
    $mc1->delete_value('shoutbox_');

**Comment by whocares-openscene** [comment]
Did you uncomment this one as well?
//require_once INCL_DIR.'function_ircbot.php';

If so check your server's error logs and see what they say

**Comment by Kongledyret** [comment]
Yes

**Comment by Kongledyret** [comment]
PHP Parse error:  syntax error, unexpected '<' <- Fixed :D
